---
- name: Test Ansible Connectivity
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping the remote hosts
      ansible.builtin.ping:
      
    - name: Deploy the configuration file from template
      template:
        src: template.j2
        dest: /etc/myconfig.conf
