---
- name: Test Ansible Connectivity
  hosts: all
  become: true  # Ensure Ansible runs with elevated privileges to modify system files
  gather_facts: true
  tasks:
    #- name: Ping the remote hosts
     # ansible.builtin.ping:
      
    - name: Deploy the configuration file from template
      template:
        src: 01.fcoe-config.yml.j2
        dest: /etc/netplan/01_fcoe_config.yaml