---
- name: Test Ansible Connectivity
  hosts: all
  become: true  # Ensure Ansible runs with elevated privileges to modify system files
  gather_facts: true
  tasks:
    #- name: Ping the remote hosts
     # ansible.builtin.ping:
    - name: Define interfaces dictionary
      set_fact:
        interfaces_dict:
          ens8:
            macaddress: "{{ ansible_facts['ens8']['macaddress'] }}"
          ens9:
            macaddress: "{{ ansible_facts['ens9']['macaddress'] }}"

    - name: Deploy the configuration file from template
      template:
          src: 01.fcoe-config.yml.j2
          dest: /etc/netplan/01_fcoe_config.yaml
    - name: Gather network facts
      ansible.builtin.setup:
        gather_subset:
          - 'network'
    - name: Gather network facts
      ansible.builtin.setup:
        gather_subset:
          - network
    - name: Find NICs MAC
      ansible.builtin.debug:
          msg: " interface {{ item }}'s MAC is {{ ansible_facts[item]['macaddress']|default(None) }}"
      with_items:
      - "{{ ansible_interfaces }}"
